### ISSUE TITLE
Feature Request: NZB via sabnzbd or nzbget

### ISSUE THREAD

**Issue by aetaric** [kubealex/k8s-mediaserver-operator#11]
**Is your feature request related to a problem? Please describe.**
While this helm chat works well for torrents, a lot of the plex community uses Usenet instead. Being able to deploy sabnzbd or nzbget via a k8s helm chart would be preferred by a large number of users in the community.

**Describe the solution you'd like**
I'd suggest converting the current jackett + transmission setup to be a bool that can enable and disable the deployment of those resources and then setting up something similar for sabnzbd or nzbget. This would allow users to select one over the other, or, both options.

In general, I would suggest this for all services. (I have a plex server on baremetal already, and wouldn't want it deployed in k8s due to the hardware required to run a library of the size I already run.)

**Describe alternatives you've considered**
Obviously manually deploying my own containers based on https://hub.docker.com/r/linuxserver/sabnzbd is an option, but not quite as clean as an all-in-one helm chart would be.

**Comment by mulbane** [comment]
I'm having an issue with this setup:
```    storage:
      pvcName: mediaserver-pvc
      size: 1000Gi
      pvcStorageClass: ""
      nfs: true
      nfsServer: REDACTED
      nfsPath: REDACTED```

Error:
```status:
  conditions:
  - lastTransitionTime: "2021-10-31T14:09:47Z"
    status: "True"
    type: Initialized
  - lastTransitionTime: "2021-10-31T14:09:50Z"
    message: 'failed to install release: rendered manifests contain a resource that
      already exists. Unable to continue with install: could not get information about
      the resource: persistentvolumes "mediaserver-pv" is forbidden: User "system:serviceaccount:mediaserver:k8s-mediaserver-operator-controller-manager"
      cannot get resource "persistentvolumes" in API group "" at the cluster scope'
    reason: InstallError
    status: "True"
    type: ReleaseFailed```

I've tested the NFS mount on other systems and it works fine, so I don't believe it's NFS permissions.

**Comment by aetaric** [comment]
@mulbane if you are using the branch mentioned in [this comment](https://github.com/kubealex/k8s-mediaserver-operator/issues/11#issuecomment-950406255) you can apply the patch I attached in [this comment](https://github.com/kubealex/k8s-mediaserver-operator/issues/11#issuecomment-953174361) and it should work. `patch k8s-mediaserver-operator-arm64.yml k8s-mediaserver-operator-arm64.txt`

That is specifically for the arm version, but the change should work fine for the amd64 version as well, just have to modify the same section of the file in the same way.

**Comment by kubealex** [comment]
@aetaric thanks for the patch, I applied it to both versions. Ingresses and deployments were not needed since they are already watched with * permission on verbs ;)

**Comment by kubealex** [comment]
@aetaric other than the NFS issue (I will probably remove the PV from the setup, and it will have to be provided manually), do you see any issues on the new version? Sabnzbd works as expected?

**Comment by aetaric** [comment]
@kubealex Yeah it does seem that those permissions weren't needed. Not sure why it was complaining about it prior, hasn't done it the last few deployment attempts....

I tore everything down and redeployed several times, but I am unable to get the sabnzbd lb to appear:
```
$ kubectl get services                                      
NAME            TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)          AGE
kubernetes      ClusterIP      10.96.0.1        <none>          443/TCP          205d
radarr          ClusterIP      10.108.202.174   <none>          7878/TCP         29s
radarr-lb       LoadBalancer   10.106.61.232    192.168.8.104   7878:30424/TCP   29s
sabnzbd         ClusterIP      10.98.94.159     <none>          8080/TCP         29s
sabnzbd-https   ClusterIP      10.106.189.92    <none>          9090/TCP         29s
sonarr          ClusterIP      10.105.92.159    <none>          8989/TCP         29s
sonarr-lb       LoadBalancer   10.105.147.118   192.168.8.103   8989:30081/TCP   29s
```

```
  sabnzbd:
    enabled: true
    container: 
      nodeSelector: {}
      port: 
        http: 8080
        https: 9090
    service:
      http:
        type: ClusterIP
        port: 8080
        nodePort: 
        extraLBService: true
      https:
        type: ClusterIP
        port: 9090
        nodePort:
        extraLBService: true
    ingress:
      enabled: false
      annotations: {}
      path: /sabnzbd
      tls:
        enabled: false
        secretName: ""
```
