### ISSUE TITLE
Nginx subpath url do not work

### ISSUE THREAD

**Issue by Rahulsharma0810** [kubealex/k8s-mediaserver-operator#30]
**Describe the bug**
The subpath URL doesn't work with the default settings. 

**To Reproduce**
spec:
  general:
    ingress_host: media.labs.rvsharma.com

```
  radarr:
    enabled: true
    container:
      nodeSelector: {}
      port: 7878
    service:
      type: ClusterIP
      port: 7878
      nodePort:
      extraLBService: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: /radarr
```

**Expected behavior**
media.labs.example.com/radarr

**logs** 

```
ingress-nginx/ingress-nginx-nginx-ingress-8555b45c5c-jncnx[ingress-nginx-nginx-ingress]: 2022/09/15 18:59:43 [error] 344#344: *17678 open() "/etc/nginx/html/radarr" failed (2: No such file or directory), client: 192.168.0.113, server: media.labs.rvsharma.com, request: "HEAD /radarr HTTP/1.1", host: "media.labs.example.com"
ingress-nginx/ingress-nginx-nginx-ingress-8555b45c5c-jncnx[ingress-nginx-nginx-ingress]: 192.168.0.113 - - [15/Sep/2022:18:59:43 +0000] "HEAD /radarr HTTP/1.1" 404 0 "-" "curl/7.79.1" "-"
```

**Environment:**
 - K8s version: 1.21+
 - CNI Plugin:  calico
 - CSI Type: longhorn

**Additional context**
Plex is working fine on the subdomain.
