### ISSUE TITLE
[BR] unable to use NFS mount as per read me

### ISSUE THREAD

**Issue by anothersmith** [kubealex/k8s-mediaserver-operator#61]
when adding NFS details to my-values.yaml the installation breaks

`helm install -f my-values.yaml k8s-mediaserver ./helm-charts/k8s-mediaserver/`

Error: INSTALLATION FAILED: YAML parse error on k8s-mediaserver/templates/jackett-resources.yml: error converting YAML to JSON: yaml: line 59: did not find expected key

`my-values.yaml`
```
general:
  storage:
    customVolume: true
  volumes:
    nfs:
      server: 192.168.0.5
      path: /opt/plexmedia/
plex:
  enabled: false

```

pods launch fine if overrides are omitted
