### ISSUE TITLE
[FR] Add an nginx security/protection container in the mix

### ISSUE THREAD

**Issue by veenarm** [kubealex/k8s-mediaserver-operator#63]
**Is your feature request related to a problem? Please describe.**
The only problem is that nothing is protected on the network, as all the 'Ingress' controllers are on the LB for the K8S cluster anyone on the network can hit any of them with out issue.

**Describe the solution you'd like**
Use the same domain but have some basic auth security before being able to access the content.

**Describe alternatives you've considered**
Transmission has some auth but it's considered not very good, and sonarr/radarr don't have any afaik.
Plex and Jellyfin (which is what I am using) both have there own AUTH attached.

**Additional context**

Personally I added this myself after the operator by using the nginx bitnami helm chart with `image: docker.io/bitnami/nginx:1.23.3-debian-11-r17`
```yaml
          volumeMounts:
            - name: nginx-server-block
              mountPath: /opt/bitnami/nginx/conf/server_blocks
            - name: nginx-htpasswd
              readOnly: true
              mountPath: /etc/nginx/passwords
```

So we load a secret with the user/pass based on how nginx generates accounts as per https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/   (using .htaccess)
 
I did this all manually, but it could be built in to 'auto generate a admin account and password for you and print it to console on first start or something'.

Example of a location block for the applications in the `nginx.conf`

```
		  location ^~ /radarr/ {
		    proxy_pass http://radarr.mediaserver.svc.cluster.local:7878;
		    proxy_pass_request_headers on;
		    proxy_buffering off;
		    proxy_set_header X-Real-IP $remote_addr;
		    proxy_set_header X-Forwarded-Host $host;
		    proxy_set_header X-Forwarded-Port $server_port;
		    auth_basic \"Restricted Content\";
		    auth_basic_user_file /etc/nginx/passwords/.htpasswd;
		  }
```
