### ISSUE TITLE
[BR] No PVC defined for Prowlarr in chart

### ISSUE THREAD

**Issue by InputObject2** [kubealex/k8s-mediaserver-operator#70]
**Describe the bug**
When configuring a custom volume for Prowlarr, the deployment is properly configured but the PVC is missing from the storage-resources.yml file.

**To Reproduce**
Deploy a K8SMediaServer with Prowlarr configuration:

```yaml
prowlarr:
  enabled: true
  volume:
      name: pvc-prowlarr-volume
      accessModes: ReadWriteOnce
      storage: 2Gi
```

**Additional context**
I did the initial push for both the volumes and prowlarr, I can contribute the fix if you'd like.
